### ISSUE TITLE
COM classes missing?

### ISSUE THREAD

**Issue by ghost** [jchv/webview2-in-mingw#2]
COM classes missing?

```
In file included from Src/main.cpp:2:
./WebView/include/WebView2.h:637:13: error: '_COM_Outptr_' has not been declared
  637 |             _COM_Outptr_  void **ppvObject);
      |             ^~~~~~~~~~~~
./WebView/include/WebView2.h:637:34: error: two or more data types in declaration of 'ppvObject'
  637 |             _COM_Outptr_  void **ppvObject);
      |                                  ^~~~~~~~~
./WebView/include/WebView2.h:753:13: error: '_COM_Outptr_' has not been declared
  753 |             _COM_Outptr_  void **ppvObject);
      |             ^~~~~~~~~~~~
./WebView/include/WebView2.h:753:34: error: two or more data types in declaration of 'ppvObject'
  753 |             _COM_Outptr_  void **ppvObject);
      |                                  ^~~~~~~~~
...
```

I used MinGW 32b, with pointing on [WebView/Win32]

**Comment by jchv** [comment]
`_COM_Outptr_` is part of Microsoft's Sourcecode Annotation Library (SAL) that is specified in `sal.h`.  `_COM_Outptr_` was added to mingw-w64 over 5 years ago, which suggests you may possibly be using a MinGW distribution that is severely out of date. Although it is by no means required to get it working, I would recommend considering using msys2 in the future since it provides a regularly maintained MinGW distribution via a package manager.

If you would like to try to get this working, try including the following file ahead of including `WebView2.h`:

https://raw.githubusercontent.com/mirror/mingw-w64/b1487f413aff83673b5b6dde3978fc1d377f6f39/mingw-w64-headers/include/sal.h

I would prefer to avoid including this in this repo here, since it will break SAL checks in Visual Studio (and possibly the build entirely.)

**Comment by ghost** [comment]
Yes, I'm using MinGW 32b, `sal.h` didn't fix the build problem, but I guess I will try later with mingw-w64.

Thank you.
