### ISSUE TITLE
CreateCoreWebViewEnvironmentWithOptions failed

### ISSUE THREAD

**Issue by ghost** [jchv/webview2-in-mingw#3]
With VS, compiling is fine, but error when running :

Call to CreateCoreWebViewEnvironmentWithOptions failed!

**Comment by jchv** [comment]
Hello,

I just gave it a shot and it seems to be working for me in VS currently, both on x86 and x64.

You may be aware of this, but because this is consistent with what happens when it is missing: Please note that this only works with the new Chromium Edge based Webview2 runtime. While Webview2 is in preview, you need to explicitly install the Webview2 runtime, or (not recommended) explicitly provide a path to another installation of Microsoft Edge (officially Webview2loader only supports Edge 86+, but actually it works fine with Edge 84.)

You can download a copy of the Webview2 runtime here:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

It would be very nice if we could fallback to EdgeHTML in case Webview2 is not available, since it is a pretty respectable browser option that already ships with Windows. Unfortunately, EdgeHTML uses WinRT-based APIs instead of COM-based APIs, meaning I will need to write asm per architecture to integrate it in such a way that it will work with MinGW. (I'll still try to take a look when I get a chance.)

**Comment by ghost** [comment]
Yes, fixed after installing Webview2 runtime, I was thinking is already shipped with Win10!

now I have a question, how to build an portable webview app ? I know the old IE lib is already shipped with Windows.. but what about WebView2 and EdgeHTML? did we can use it as a static linking for portability?

**Comment by ghost** [comment]
I'm talking about using MSC compiler, I know with MinGW will need more extra work!

**Comment by jchv** [comment]
Ahh, you may be quite interested in the [webview/webview](https://github.com/webview/webview) library - it provides a single-header with fallback for EdgeHTML. You can even compile it as a library with MSVC and then link it into your MinGW application as a dependency, which does add an additional DLL dependency alongside WebView2Loader, but should do roughly what you want.

**Comment by ghost** [comment]
Thank you @jchv, I know [it](webview/webview), but I still confused about EdgeHTML with WebView2Loader!, I mean I taught it's two different projects no?!

**Comment by ghost** [comment]
EdgeHTML is a discontinued project! so I guess I need to use only WebView2 as the new Microsoft project?

**Comment by jchv** [comment]
EdgeHTML is discontinued, but it is currently shipped with Windows and will for the indefinite future. However, WebView2 is still just a preview and is not shipped with Windows. EdgeHTML does not need WebView2Loader at all - EdgeHTML is integrated into the WinRT API. WebView2Loader is purely for integrating the new Chromium-based Microsoft Edge into applications, whereas EdgeHTML is the old browser engine from the original Microsoft Edge that forked Trident/MSHTML (which is an even older browser engine, still shipped with Windows.)

Therefore, if you want the best experience, it is probably recommended to use WebView2 if it is available, and EdgeHTML if it is not, which is why I recommend using the github.com/webview/webview project - it provides this for you.

**Comment by jchv** [comment]
I'm closing this issue. I don't think there is much else I can add, and the user who created it has deleted their account. If anyone comes across this thread and has any issues, just create a new issue or re-open this one.
